Repository collaborationFactory/github-actions, pull requests merged in 2022-11, with the labels that each got.

#13 PFM-ISSUE-11253 - Fix package peerDependencies
  tools/scripts/artifacts/nx-project.ts
Labels: PR: Needs Review

#15 PFM-ISSUE-11304 - Fix libraries publishing
  tools/scripts/artifacts/nx-project.ts
Labels: PR: Needs Review

#16 PFM-ISSUE-11273 replaced hardcoded scope
  tools/scripts/artifacts/nx-project.ts
  tools/scripts/artifacts/utils.test.ts
  tools/scripts/artifacts/utils.ts
Labels: PR: Needs Review

#17 PFM-ISSUE-11393 - Fix percy in main branch
  .github/workflows/fe-e2e.yml
  tools/scripts/artifacts/nx-project.ts
  tools/scripts/artifacts/utils.test.ts
  tools/scripts/artifacts/utils.ts
  tools/scripts/run-many/affected-projects.ts
  tools/scripts/run-many/run-many.ts
Labels: PR: Working

#21 PFM-ISSUE-11450 - Make Percy optional in reusable actions
  .github/workflow-templates/fe/fe-main.yml
  .github/workflow-templates/fe/fe-pr.yml
  .github/workflows/fe-e2e.yml
  tools/scripts/run-many/run-many.ts
Labels: PR: Needs Review

#22 PFM-ISSUE-11470 - Exclude e2e from main ci if PERCY_TOKEN is not provided
  .github/workflow-templates/fe/fe-main.yml
  .github/workflows/fe-e2e.yml
Labels: PR: Needs Review

#23 PFM-ISSUE-11322 only publish snapshots with SourceMaps
  tools/scripts/artifacts/nx-project.ts
Labels: PR: Ready to Merge

#24 PFM-ISSUE-11498 - Fix e2e ci in reusable actions
  .github/workflow-templates/fe/fe-main.yml
  .github/workflows/fe-e2e.yml
  tools/scripts/artifacts/nx-project.ts
  tools/scripts/run-many/run-many.ts
Labels: PR: Needs Review

#25 PFM-ISSUE-11504 - Fix Percy parallel builds
  tools/scripts/run-many/run-many.ts
Labels: PR: Needs Review
