Repository collaborationFactory/github-actions, pull requests merged in 2024-12, with the labels that each got.

#77 PFM-ISSUE-28574 - Use github variables in code quality workflow
  .github/workflows/fe-code-quality.yml
  tools/scripts/artifacts/artifacts-handler.ts
  tools/scripts/artifacts/cleanup-snapshots.ts
  tools/scripts/artifacts/nx-project.ts
  tools/scripts/artifacts/types.ts
Labels: enhancement, PR: Needs Review

#78 PFM-ISSUE-28573 - Fix usage of npm unpublish in delete snapshot workflow
  tools/scripts/artifacts/nx-project.ts
Labels: bug, PR: Needs Review

#79 PFM-ISSUE-28250 fix parallelization of e2e tests
  tools/scripts/run-many/affected-projects.ts
  tools/scripts/run-many/run-many.ts
Labels: PR: Needs Review
